spring.application.name=demo

# 資料庫連線 (請確保 esun 資料庫已在 pgAdmin 建立)
spring.datasource.url=jdbc:postgresql://localhost:5432/esun
spring.datasource.username=postgres
spring.datasource.password=dd900102

# JPA 設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT 需要關閉預設的 Session
spring.main.allow-bean-definition-overriding=true